---
- name: Deploy Site-B
  hosts: siteb
  become: yes
  become_user: student8

  tasks:
  - name: install docker preqequisities
    pip:
      name: docker

  - name: launch the apache-simple container on the site-b nodes
    docker_container:
      name: apache-simple
      image: quay.io/helpme1000/ansible-for-devops-siteb
      ports:
        - "8080:8080"
